# fly.toml app configuration file generated for calypso-microservice-files on 2023-07-25T16:23:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "calypso-microservice-files"
primary_region = "ams"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0